Prevent empty tabs prop from causing fatal error
TypeError: key(): Argument #1 ($array) must be of type array, null given

Caused by registering a meta box manually outside of wp-libs